# Generated by Django 4.0.3 on 2022-04-02 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='is_checked',
        ),
        migrations.AlterField(
            model_name='homework',
            name='logo',
            field=models.ImageField(max_length=255, upload_to='homework/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='subject',
            field=models.CharField(max_length=50, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
